// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAymkqQRw7fF7CdkfGCul11QqCEq-VX8ao',
    appId: '1:182142660846:web:621b13cef939a5fa2683ff',
    messagingSenderId: '182142660846',
    projectId: 'rentacar-52d29',
    authDomain: 'rentacar-52d29.firebaseapp.com',
    storageBucket: 'rentacar-52d29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZzGJltF484LsftJ7XrOuGc3v8WZioK74',
    appId: '1:182142660846:android:5c274486aead69512683ff',
    messagingSenderId: '182142660846',
    projectId: 'rentacar-52d29',
    storageBucket: 'rentacar-52d29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxOBD7SksOSNI17IoK9uj9zD5XgLMnN4I',
    appId: '1:182142660846:ios:9419b82910e2ac7a2683ff',
    messagingSenderId: '182142660846',
    projectId: 'rentacar-52d29',
    storageBucket: 'rentacar-52d29.appspot.com',
    iosBundleId: 'com.example.rentacar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxOBD7SksOSNI17IoK9uj9zD5XgLMnN4I',
    appId: '1:182142660846:ios:9419b82910e2ac7a2683ff',
    messagingSenderId: '182142660846',
    projectId: 'rentacar-52d29',
    storageBucket: 'rentacar-52d29.appspot.com',
    iosBundleId: 'com.example.rentacar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAymkqQRw7fF7CdkfGCul11QqCEq-VX8ao',
    appId: '1:182142660846:web:2492585274b8c39b2683ff',
    messagingSenderId: '182142660846',
    projectId: 'rentacar-52d29',
    authDomain: 'rentacar-52d29.firebaseapp.com',
    storageBucket: 'rentacar-52d29.appspot.com',
  );

}